actions:
  - read
  - reading
  - favorite
  - unfavorite
  - like
  - unlike
  - write
  - comment
  - delete comment
  - follow
  - unfollow
  - request

book:
  read: read
  reading: reading
  
rate:
  content: content
  design: design
  type:
    score: score

place:
  right: right

statuses:
  reading: 0
  read: 1

request:
  states:
    - pending
    - accepted
    - rejected

paginate:
  per_page: 10
  books_per_page_size: 10
  reviews_per_page: 10
