actions:
  - read
  - reading
  - favorite
  - unfavorite
  - like
  - unlike
  - write
  - comment
  - delete comment
  - follow
  - unfollow
  - request

paginate:
  per_page: 10
  books_per_page_size: 10
  reviews_per_page: 10
